// log in as Troels
POST https://localhost:7233/auth/login
Content-Type: application/json

{
  "username": "string",
  "password": "string"
}

###

POST https://localhost:7233/post/
Content-Type: application/json
{
  "title": "Second post on not reddit!",
  "content": "Pretty cool reddit clone not gonna lie."
}
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiJkYTVkZjdmYS0xZTA2LTQyYmYtOTJhYy1lYzkyODVjMjg2ZWQiLCJpYXQiOiIxMC4xMS4yMDIyIDEzOjM1OjE3IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InN0cmluZyIsIlVzZXJuYW1lIjoic3RyaW5nIiwiRW1haWwiOiJzdHJpbmciLCJJZCI6IjEiLCJleHAiOjE2NjgwOTA5MTcsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.hLIY6xqB1qxSYlviauFh1O7IiMviOH0EO6J0CM33cdVjvOab1qHwa43TNCbT46mb52eAWNNUkMkJPEnBQLRiyA